name: start imread_benchmark on dispath

on: workflow_dispatch

jobs:
  start_imread_benchmark:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    env:
      RESULT_PATH: /tmp/benchmark_result.txt
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: benchmark
      run: |
        echo "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" > ${{ env.RESULT_PATH }}
        python imread_benchmark.py >> ${{ env.RESULT_PATH }}
    - name: create issue
      uses: peter-evans/create-issue-from-file@v4
      with:
        title: imread_benchmark
        content-filepath: ${{ env.RESULT_PATH }}
        labels: benchmark